# Generated by Django 4.2.4 on 2023-08-16 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tezza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assembler',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='assembled_orders',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Сборщик',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='assembling_end',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Завершение сборки',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='assembling_start',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Начало сборки',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name='Стоимость доставки',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_tracking_number',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name='Трек номер доставки',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='picked_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Упакован',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='picker',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='picked_orders',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Упаковщик',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Отправлен',
            ),
        ),
    ]
