# Generated by Django 4.2.4 on 2024-01-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0002_alter_order_assembler_alter_order_assembling_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='side',
            field=models.CharField(choices=[('L', 'Левый'), ('R', 'Правый')], default='L', max_length=8, null=True, verbose_name='Сторона'),
        ),
    ]
