# Generated by Django 4.2.4 on 2024-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0003_alter_product_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='side_point',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Признак для стороны'),
        ),
    ]
