# Generated by Django 4.2.4 on 2024-09-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0005_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_for_assembler',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий для сборщика'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment_for_manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий для менеджера'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment_for_picker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий для упаковщика'),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='side',
            field=models.CharField(choices=[('L', 'Слева'), ('R', 'Справа')], default='L', max_length=8, null=True, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Артикул'),
        ),
    ]
