# Generated by Django 4.2.4 on 2024-10-09 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0006_order_comment_for_assembler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Дизайнер',
                'verbose_name_plural': 'Дизайнеры',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='assembled_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True, verbose_name='Дата и время завершения сборки'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designer', to='tezza.designer', verbose_name='Дизайнер'),
        ),
    ]
