# Generated by Django 4.2.4 on 2024-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0008_alter_orderitem_assembled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='assembled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения сборки'),
        ),
    ]
