# Generated by Django 4.2.4 on 2024-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0009_alter_orderitem_assembled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('items', models.IntegerField(default=0, verbose_name='Количество изделий')),
                ('added_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время завершения сборки')),
            ],
            options={
                'verbose_name': 'План на месяц',
                'verbose_name_plural': 'Планы на месяц',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='added_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время добавления изделия'),
        ),
    ]
