# Generated by Django 4.2.4 on 2024-10-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0010_monthlyplan_orderitem_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='added_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время создания плана'),
        ),
    ]
