# Generated by Django 4.2.4 on 2024-10-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0011_order_completed_at_alter_monthlyplan_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
