# Generated by Django 4.2.4 on 2024-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0013_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('cut', 'Резка'), ('assembly', 'Сборка'), ('assembled', 'Собран'), ('coloring', 'Покраска')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
