# Generated by Django 4.2.4 on 2024-10-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0014_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='side',
            field=models.CharField(blank=True, choices=[('L', 'Слева'), ('R', 'Справа')], max_length=8, null=True, verbose_name='Сторона'),
        ),
    ]
