# Generated by Django 4.2.4 on 2024-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0015_alter_product_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
