# Generated by Django 4.2.4 on 2024-10-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0017_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_for_sender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий для упаковщика'),
        ),
        migrations.AddField(
            model_name='product',
            name='size2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Второй размер, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Размер, см'),
        ),
    ]
