# Generated by Django 4.2.4 on 2025-02-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0021_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер'),
        ),
    ]
