# Generated by Django 4.2.4 on 2025-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0022_alter_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_payer',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('company', 'Компания')], max_length=10, null=True, verbose_name='Оплата доставки'),
        ),
    ]
