# Generated by Django 5.1.6 on 2025-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0023_order_delivery_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Размер, см'),
        ),
    ]
