# Generated by Django 5.1.6 on 2025-06-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezza', '0024_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_payer',
            field=models.CharField(choices=[('customer', 'Получатель'), ('company', 'Отправитель')], max_length=10, null=True, verbose_name='Оплата доставки'),
        ),
    ]
